/**
  ******************************************************************************
  * @file	 	Global_Init.c
  * @author  	Left Radio
  * @version
  * @date
  * @brief		sourse
  ******************************************************************************
**/

/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx.h"
#include "usbd_audio_core.h"
#include "Si5351.h"
#include "Si5351_registers.h"

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
#define SI5351_I2C_ADDR				((uint8_t)0xC0)

#define SI5351_RUN					(ENABLE)
#define SI5351_STOP					(DISABLE)

/* Private macro -------------------------------------------------------------*/
/* Private function prototypes -----------------------------------------------*/
static void Si5351_Configuration_Registers(void);
static void Si5351_DeInit(void);
static void Si5351_Start(void);
static void Si5351_Stop(void);

/* Private variables ---------------------------------------------------------*/
volatile Si5351_TypeDef si5351 =
{
    /* Si5351_TypeDef */
	AUDIO_FREQUENCY * 512,
    1,
    SI5351_STOP,
    Si5351_Configuration_Registers,
    Si5351_DeInit,
    Si5351_Start,
    Si5351_Stop,
};


/* Extern function -----------------------------------------------------------*/
/* Private functions ---------------------------------------------------------*/

/**
  * @brief  Si5351_Configuration_Registers
  * @param  None
  * @retval None
  */
static void Si5351_Configuration_Registers(void)
{
    uint8_t i;
    uint8_t *pSI5351_Map = (uint8_t*)SI5351_RegistersMap_24M;
    int res = 0;

    if(si5351.State == SI5351_STOP)
    {
    	I2C_Configuration(100000);

//    	switch(si5351.Frequency)
//    	{
//    	case 22579200:
//    		pSI5351_Map = (uint8_t*)SI5351_RegistersMap_22_579;
//    		break;
//    	case 24576000:
//    		pSI5351_Map = (uint8_t*)SI5351_RegistersMap_24M;
//    		break;
//
//    	}


    	/*
    	 * Configure Si5351, see documentation on silabs.com for more detals
    	 */

    	/* Disable Outputs */
    	Si5351_Stop();

    	/* Powerdown all output drivers */
    	for(i = 16; i < 24; i++)
    	{
    		res = I2C_Write(I2C1, SI5351_I2C_ADDR, i, 0x80);
    		if(res != 0) return;
    	}

    	/* Write new configuration to device using the contents of the register map
    	 * generated by ClockBuilder Desktop.
    	 */
    	for(i = 0; i < 233; i += 2)
    	{
    		res = I2C_Write(I2C1, SI5351_I2C_ADDR, *pSI5351_Map, *(pSI5351_Map + 1));
    		if(res != 0) return;
    		pSI5351_Map += 2;
    	}

    	/* Apply PLLA and PLLB soft reset */
    	res = I2C_Write(I2C1, SI5351_I2C_ADDR, 177, 0xAC);
    	if(res != 0) return;

    	/* Enable Outputs */
    	Si5351_Start();

    	/* Update si5351 state */
    	si5351.State = SI5351_RUN;
    }
}


/**
  * @brief  Si5351_Configuration_Registers
  * @param  None
  * @retval None
  */
static void Si5351_DeInit(void)
{
	if(si5351.State != SI5351_STOP)
	{
		/* Stop oscillation */
		Si5351_Stop();

		/* DeInit the I2C periph */
		I2C_DeConfiguration();

		/* Update si5351 state */
		si5351.State = SI5351_STOP;
	}
}


/**
  * @brief  Enable outputs, AN619 on silabs.com
  * @param  None
  * @retval None
  */
static void Si5351_Start(void)
{
	I2C_Write(I2C1, SI5351_I2C_ADDR, 3, 0x00);
}


/**
  * @brief  Disable outputs, AN619 on silabs.com
  * @param  None
  * @retval None
  */
static void Si5351_Stop(void)
{
	I2C_Write(I2C1, SI5351_I2C_ADDR, 3, 0xFF);
}





/*********************************************************************************************************
      END FILE
*********************************************************************************************************/
